#ifndef GLMS_CONSTANTS_H
#define GLMS_CONSTANTS_H

#define GLMS_MEMO_AST_PAGE_CAPACITY 30000
#define GLMS_ARENA_AST_CAPACITY (GLMS_MEMO_AST_PAGE_CAPACITY * 2)
#define GLMS_GC_SWEEP_THRESHOLD 64
#define GLMS_GC_SWEEP_ITER (GLMS_GC_SWEEP_THRESHOLD / 2)

#define GLMS_FUNC_OVERLOAD_TEMPLATE "__func_overload__%s"

#endif
