#ifndef JSCRIPT_AST_H
#define JSCRIPT_AST_H

typedef enum {
JSCRIPT_AST_TYPE_ID,
JSCRIPT_AST_TYPE_STRING,
JSCRIPT_AST_TYPE_NUMBER,
JSCRIPT_AST_TYPE_BINOP,
JSCRIPT_AST_TYPE_UNOP
} JSCRIPTASTType;

typedef struct {
  JSCRIPTASTType type;
} JSCRIPTAST;

#endif
