#ifndef JSCRIPT_FPTR_H
#define JSCRIPT_FPTR_H

struct JSCRIPT_AST_STRUCT;
struct JSCRIPT_EVAL_STRUCT;
struct JSCRIPT_JSCRIPTAST_LIST_STRUCT;

typedef struct JSCRIPT_AST_STRUCT* (*JSCRIPTFPTR)(struct JSCRIPT_EVAL_STRUCT* eval, struct JSCRIPT_AST_STRUCT* ast, struct JSCRIPT_JSCRIPTAST_LIST_STRUCT* args);
#endif
