#ifndef JSCRIPT_TOKEN_H
#define JSCRIPT_TOKEN_H
#include <jscript/string_view.h>

typedef enum {
  JSCRIPT_TOKEN_TYPE_NONE,
  JSCRIPT_TOKEN_TYPE_LBRACE,
  JSCRIPT_TOKEN_TYPE_RBRACE,
  JSCRIPT_TOKEN_TYPE_LBRACKET,
  JSCRIPT_TOKEN_TYPE_RBRACKET,
  JSCRIPT_TOKEN_TYPE_LPAREN,
  JSCRIPT_TOKEN_TYPE_RPAREN,
  JSCRIPT_TOKEN_TYPE_SEMI,
  JSCRIPT_TOKEN_TYPE_COMMA,
  JSCRIPT_TOKEN_TYPE_COLON,
  JSCRIPT_TOKEN_TYPE_ID,
  JSCRIPT_TOKEN_TYPE_STRING,
  JSCRIPT_TOKEN_TYPE_NUMBER,
  JSCRIPT_TOKEN_TYPE_ADD,
  JSCRIPT_TOKEN_TYPE_MUL,
  JSCRIPT_TOKEN_TYPE_SUB,
  JSCRIPT_TOKEN_TYPE_DIV,
  JSCRIPT_TOKEN_TYPE_PERCENT,
  JSCRIPT_TOKEN_TYPE_EQUALS,
  JSCRIPT_TOKEN_TYPE_EQUALS_EQUALS,
  JSCRIPT_TOKEN_TYPE_GT,
  JSCRIPT_TOKEN_TYPE_LT,
  JSCRIPT_TOKEN_TYPE_GTE,
  JSCRIPT_TOKEN_TYPE_LTE
} JSCRIPTTokenType;

typedef struct {
  JSCRIPTTokenType type;
  JSCRIPTStringView value;
  char c;
} JSCRIPTToken;

#endif
