#ifndef JSCRIPT_TOKEN_H
#define JSCRIPT_TOKEN_H
#include <jscript/string_view.h>
#include <jscript/macros.h>

#define JSCRIPT_FOREACH_TOKEN_TYPE(TOK)         \
  TOK(JSCRIPT_TOKEN_TYPE_NONE)                  \
  TOK(JSCRIPT_TOKEN_TYPE_EOF)\
  TOK(JSCRIPT_TOKEN_TYPE_LBRACE)\
  TOK(JSCRIPT_TOKEN_TYPE_RBRACE)\
  TOK(JSCRIPT_TOKEN_TYPE_LBRACKET)\
  TOK(JSCRIPT_TOKEN_TYPE_RBRACKET)\
  TOK(JSCRIPT_TOKEN_TYPE_LPAREN)\
  TOK(JSCRIPT_TOKEN_TYPE_RPAREN)\
  TOK(JSCRIPT_TOKEN_TYPE_SEMI)\
  TOK(JSCRIPT_TOKEN_TYPE_COMMA)\
  TOK(JSCRIPT_TOKEN_TYPE_COLON)\
  TOK(JSCRIPT_TOKEN_TYPE_DOT)\
  TOK(JSCRIPT_TOKEN_TYPE_ID)\
  TOK(JSCRIPT_TOKEN_TYPE_STRING)\
  TOK(JSCRIPT_TOKEN_TYPE_NUMBER)\
  TOK(JSCRIPT_TOKEN_TYPE_ADD)\
  TOK(JSCRIPT_TOKEN_TYPE_ADD_EQUALS)\
  TOK(JSCRIPT_TOKEN_TYPE_MUL)\
  TOK(JSCRIPT_TOKEN_TYPE_SUB)\
  TOK(JSCRIPT_TOKEN_TYPE_DIV)\
  TOK(JSCRIPT_TOKEN_TYPE_PERCENT)\
  TOK(JSCRIPT_TOKEN_TYPE_EQUALS)\
  TOK(JSCRIPT_TOKEN_TYPE_EQUALS_EQUALS)\
  TOK(JSCRIPT_TOKEN_TYPE_GT)\
  TOK(JSCRIPT_TOKEN_TYPE_LT)\
  TOK(JSCRIPT_TOKEN_TYPE_GTE)\
  TOK(JSCRIPT_TOKEN_TYPE_LTE)\
  TOK(JSCRIPT_TOKEN_TYPE_SPECIAL_FOR)\
  TOK(JSCRIPT_TOKEN_TYPE_SPECIAL_FALSE)\
  TOK(JSCRIPT_TOKEN_TYPE_SPECIAL_TRUE)\
  TOK(JSCRIPT_TOKEN_TYPE_SPECIAL_IF)\
  TOK(JSCRIPT_TOKEN_TYPE_SPECIAL_ELSE)\
  TOK(JSCRIPT_TOKEN_TYPE_SPECIAL_FUNCTION)\
  TOK(JSCRIPT_TOKEN_TYPE_SPECIAL_RETURN)

typedef enum {
  JSCRIPT_FOREACH_TOKEN_TYPE(JSCRIPT_GENERATE_ENUM)
} JSCRIPTTokenType;

static const char *JSCRIPT_TOKEN_TYPE_STR[] = {
    JSCRIPT_FOREACH_TOKEN_TYPE(JSCRIPT_GENERATE_STRING)
};

typedef struct {
  JSCRIPTTokenType type;
  JSCRIPTStringView value;
  char c;
} JSCRIPTToken;

#endif
